
# ${title}
# Generated by AjGenesis
# Author: ${author}

require 'sinatra'

get '/' do
  @title = "${title}"
  erb :index
end
<#
entities.each do |entity|
#>

get '/${entity.name}' do
    @title = '${entity.setdescriptor}'
    @${entity.name}_list = [ '${entity.name} 1', '${entity.name} 2' ]
    erb :${entity.name}list
end
<#
end
#>

get '/about' do
  @title = "About"
  erb :about
end